name: "tslint"
on:
  push:
    # paths:
    #   - mahjong/**
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  eslint:
    defaults:
      run:
        working-directory: mahjong_ts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ls -lah
        run: ls -lah
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true
      - name: vite build
        run: yarn dev
        env:
          CI: true
